version: '3.1'

services:
  minio:
    image: underload:0.0.1
    restart: always
    environment:
      MYKEY: myval
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/"]
      interval: 30s
      timeout: 20s
      retries: 3
    ports:
      - 8080:8080
    volumes:
      - /Users/eliott.legendre/Desktop/test_mount/:/mnt/


# docker run -p 5000:5000 -v /Users/eliott.legendre/Desktop/test_mount/:/mnt/ underload:1.0.dev0
# docker run -p 8080:8080 --rm -v /Users/eliott.legendre/Desktop/test_mount/:/mnt/ underload:1.0.dev0